"""Phase-A transaction protocols. UUIDs are generated by the application, not SQL."""
from __future__ import annotations

import hashlib
import json
import logging
from collections.abc import Iterator, Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Any, cast
from uuid import UUID

from uuid6 import uuid7

from common.logging import log_event
from persistence.repositories import (
    AccountRepository,
    ConversationRepository,
    IdempotencyRepository,
    MessageRepository,
    OutboxRepository,
    RunRepository,
    SessionRepository,
    WorkflowExecutionRepository,
)
from persistence.uow import UnitOfWork, retryable_transaction

from .errors import (
    ConversationBusy,
    IdempotencyConflict,
    ResourceNotFound,
    RunNotCancellable,
    RunNotRetryable,
)
from .sessions import ConversationSessionService

logger = logging.getLogger("HpAgent.WebRun")


def _id() -> UUID:
    """Generate application-owned UUIDv7 values; PostgreSQL needs no UUID extension."""
    return uuid7()


def _digest(value: object) -> bytes:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).digest()


@dataclass(frozen=True)
class CommandResult(Mapping[str, Any]):
    """A frozen command body plus the exact status an HTTP adapter must replay."""

    response_status: int
    body: dict[str, Any]
    replayed: bool = field(default=False, compare=False)
    resource_reused: bool = field(default=False, compare=False)

    def __getitem__(self, key: str) -> Any:
        return self.body[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self.body)

    def __len__(self) -> int:
        return len(self.body)


class CommandService:
    def __init__(self, database_url: object):
        self.database_url = database_url
        self.accounts = AccountRepository()
        self.conversations = ConversationRepository()
        self.messages = MessageRepository()
        self.runs = RunRepository()
        self.sessions = SessionRepository()
        self.session_service = ConversationSessionService(database_url)
        self.workflows = WorkflowExecutionRepository()
        self.idempotency = IdempotencyRepository()
        self.outbox = OutboxRepository()

    @retryable_transaction
    def create_conversation(self, account_id: UUID, key: str, title: str = "") -> CommandResult:
        payload = {"title": title}
        with UnitOfWork(self.database_url) as uow:
            existing = self._claim(uow, account_id, "create_conversation", key, payload)
            if existing:
                return existing
            if not self.accounts.require_active(uow, account_id):
                raise ResourceNotFound()
            conversation_id = _id()
            self.conversations.create(uow, conversation_id, account_id, title)
            row = uow.execute(
                "SELECT * FROM conversations WHERE account_id=%s AND conversation_id=%s",
                (account_id, conversation_id),
            ).fetchone()
            result = {
                "conversation_id": str(conversation_id),
                "conversation": self._conversation_dto(row),
            }
            self._complete(uow, account_id, "create_conversation", key, 201, result)
            return CommandResult(201, result)

    @retryable_transaction
    def send_message(
        self,
        account_id: UUID,
        conversation_id: UUID,
        key: str,
        content: str,
        agent_strategy: str = "react",
    ) -> CommandResult:
        if agent_strategy not in {"react", "plan_and_execute"}:
            raise ValueError("unsupported agent strategy")
        # Preserve the pre-durable request hash for the default strategy so
        # in-flight/retained idempotency keys remain replayable after upgrade.
        payload = {"conversation_id": str(conversation_id), "content": content}
        if agent_strategy != "react":
            payload["agent_strategy"] = agent_strategy
        with UnitOfWork(self.database_url) as uow:
            existing = self._claim(uow, account_id, "send_message", key, payload)
            if existing:
                return existing
            conversation = self.conversations.lock_active(uow, account_id, conversation_id)
            if not conversation:
                raise ResourceNotFound()
            retained = self.messages.find_initial_by_client_request(uow, account_id, UUID(key))
            if retained:
                if retained["conversation_id"] != conversation_id or retained["content"] != content:
                    raise IdempotencyConflict()
                result = self._send_result_for_run(uow, retained["run_id"])
                self._complete(uow, account_id, "send_message", key, 202, result)
                return CommandResult(202, result)
            if self.runs.has_active(uow, conversation_id):
                raise ConversationBusy()
            session_id = self.session_service.get_or_create_in_locked_conversation(
                uow, account_id, conversation_id
            )
            allocated = self.conversations.allocate_messages(
                uow, account_id, conversation_id, 2
            )
            user_message_id, run_id, assistant_message_id = _id(), _id(), _id()
            workflow_id = f"hpagent-web-run-{run_id}"
            self.messages.insert_user(
                uow, user_message_id, account_id, conversation_id, content,
                allocated - 1, UUID(key)
            )
            self.runs.insert(
                uow, run_id, account_id, conversation_id, session_id, user_message_id,
                workflow_id, allocated - 1, agent_strategy=agent_strategy
            )
            self.messages.insert_assistant(
                uow, assistant_message_id, account_id, conversation_id, allocated, run_id
            )
            self._outbox(uow, account_id, conversation_id, run_id, "start_run")
            result = self._send_result_for_run(uow, run_id)
            self._complete(uow, account_id, "send_message", key, 202, result)
            log_event(logger, logging.INFO, "run_created", "run", run_id=str(run_id),
                      conversation_id=str(conversation_id), session_id=str(session_id), status="started")
            return CommandResult(202, result)

    @retryable_transaction
    def cancel_run(self, account_id: UUID, run_id: UUID, key: str) -> CommandResult:
        """Cancel a queued Run before any Workflow execution exists.

        The Temporal-facing branch is deliberately not implemented here: Phase D
        owns it.  This branch still follows the approved Phase-A atomic terminal
        transaction and leaves the existing start event for a future dispatcher to
        observe and skip.
        """
        payload = {"run_id": str(run_id)}
        with UnitOfWork(self.database_url) as uow:
            existing = self._claim(uow, account_id, "cancel_run", key, payload)
            if existing:
                return existing
            conversation_id = self.runs.discover_conversation(uow, account_id, run_id)
            if conversation_id is None:
                raise ResourceNotFound()
            self.conversations.get_for_account(uow, account_id, conversation_id, lock=True)
            run = self.runs.get_for_account(uow, account_id, run_id, lock=True)
            if run is None:
                raise ResourceNotFound()
            if run["status"] in ("completed", "failed"):
                raise RunNotCancellable()
            if run["status"] == "cancelled":
                result = self._snapshot_for_run(uow, run_id)
                result.update({"run_id": str(run_id), "status": "cancelled"})
                response_status = 200
            elif run["status"] == "queued" and not self.workflows.has_current(uow, run_id):
                self._set_terminal(
                    uow, account_id, run["conversation_id"], run_id, "cancelled"
                )
                result = self._snapshot_for_run(uow, run_id)
                result.update({"run_id": str(run_id), "status": "cancelled"})
                response_status = 200
            else:
                self.runs.set_cancelling(uow, run_id)
                self._outbox(uow, account_id, run["conversation_id"], run_id, "cancel_run")
                result = self._snapshot_for_run(uow, run_id)
                result.update({"run_id": str(run_id), "status": "cancelling"})
                response_status = 202
            self._complete(
                uow, account_id, "cancel_run", key, response_status, result
            )
            return CommandResult(response_status, result)

    @retryable_transaction
    def retry_run(self, account_id: UUID, source_run_id: UUID, key: str) -> CommandResult:
        payload = {"run_id": str(source_run_id)}
        with UnitOfWork(self.database_url) as uow:
            existing = self._claim(uow, account_id, "retry_run", key, payload)
            if existing:
                return existing
            conversation_id = self.runs.discover_conversation(uow, account_id, source_run_id)
            if conversation_id is None:
                raise ResourceNotFound()
            conversation = self.conversations.get_for_account(
                uow, account_id, conversation_id, lock=True
            )
            source = self.runs.get_for_account(uow, account_id, source_run_id, lock=True)
            if source is None:
                raise ResourceNotFound()
            child = self.runs.direct_retry(uow, source_run_id)
            if child:
                result = self._retry_result_for_run(uow, source_run_id, child["run_id"])
                response_status = 200
                resource_reused = True
            else:
                if source["status"] not in ("failed", "cancelled"):
                    raise RunNotRetryable()
                if conversation is None or conversation["status"] != "active":
                    raise ResourceNotFound()
                if self.runs.has_active(uow, source["conversation_id"]):
                    raise ConversationBusy()
                session_id = self.session_service.get_or_create_in_locked_conversation(
                    uow, account_id, source["conversation_id"]
                )
                sequence = self.conversations.allocate_messages(
                    uow, account_id, source["conversation_id"], 1
                )
                run_id = _id()
                assistant_message_id = _id()
                self.runs.insert(
                    uow, run_id, account_id, source["conversation_id"], session_id,
                    source["trigger_message_id"], f"hpagent-web-run-{run_id}",
                    source["context_message_seq"], source_run_id,
                    str(source.get("agent_strategy") or "react"),
                )
                self.messages.insert_assistant(
                    uow, assistant_message_id, account_id, source["conversation_id"],
                    sequence, run_id
                )
                self._outbox(uow, account_id, source["conversation_id"], run_id, "start_run")
                result = self._retry_result_for_run(uow, source_run_id, run_id)
                response_status = 202
                resource_reused = False
            self._complete(
                uow, account_id, "retry_run", key, response_status, result
            )
            return CommandResult(
                response_status, result, resource_reused=resource_reused
            )

    @retryable_transaction
    def start_run(self, account_id: UUID, run_id: UUID) -> bool:
        """Move a queued Run to running through the formal lifecycle boundary."""
        with UnitOfWork(self.database_url) as uow:
            run = self._lock_owned_run(uow, account_id, run_id)
            if run["status"] == "running":
                return True
            if run["status"] != "queued":
                return False
            changed = uow.execute(
                "UPDATE runs SET status='running',started_at=now(),version=version+1,"
                "updated_at=now() WHERE run_id=%s AND status='queued' RETURNING run_id",
                (run_id,),
            ).fetchone()
            return changed is not None

    @retryable_transaction
    def complete_run(self, account_id: UUID, run_id: UUID, content: str) -> bool:
        """Lifecycle adapter entrypoint; callers invoke it only after external work."""
        with UnitOfWork(self.database_url) as uow:
            run = self._lock_owned_run(uow, account_id, run_id)
            if run["status"] in ("completed", "failed", "cancelled"):
                return bool(run["status"] == "completed")
            if run["status"] not in ("running", "cancelling"):
                raise ConversationBusy()
            self.messages.set_terminal(uow, run_id, "completed", content)
            self.runs.set_terminal(uow, run_id, "completed")
            self._outbox(uow, account_id, run["conversation_id"], run_id, "retain_memory")
            self._outbox(uow, account_id, run["conversation_id"], run_id, "publish_terminal_event", "completed")
            log_event(logger, logging.INFO, "run_completed", "run", run_id=str(run_id),
                      execution_id=str(run_id), account_id=str(account_id),
                      conversation_id=str(run["conversation_id"]), surface="web",
                      status="success", run_status="completed")
            return True

    @retryable_transaction
    def fail_run(self, account_id: UUID, run_id: UUID, failure_code: str, failure_message: str | None = None) -> bool:
        """Atomically record a safe terminal failure and its notification."""
        with UnitOfWork(self.database_url) as uow:
            run = self._lock_owned_run(uow, account_id, run_id)
            if run["status"] in ("completed", "failed", "cancelled"):
                return bool(run["status"] == "failed")
            self.messages.set_terminal(uow, run_id, "failed")
            self.runs.set_terminal(uow, run_id, "failed", failure_code, failure_message)
            self._outbox(uow, account_id, run["conversation_id"], run_id, "publish_terminal_event", "failed")
            log_event(logger, logging.ERROR, "run_failed", "run", run_id=str(run_id),
                      execution_id=str(run_id), account_id=str(account_id),
                      conversation_id=str(run["conversation_id"]), surface="web",
                      status="failed", run_status="failed", error_code=failure_code)
            return True

    @retryable_transaction
    def cancelled_run(self, account_id: UUID, run_id: UUID) -> bool:
        """Converge a Workflow cancellation callback into one atomic terminal fact."""
        with UnitOfWork(self.database_url) as uow:
            run = self._lock_owned_run(uow, account_id, run_id)
            if run["status"] in ("completed", "failed", "cancelled"):
                return bool(run["status"] == "cancelled")
            self.messages.set_terminal(uow, run_id, "aborted")
            self.runs.set_terminal(uow, run_id, "cancelled")
            self._outbox(
                uow, account_id, run["conversation_id"], run_id,
                "publish_terminal_event", "cancelled"
            )
            log_event(logger, logging.INFO, "run_cancelled", "run", run_id=str(run_id),
                      execution_id=str(run_id), account_id=str(account_id),
                      conversation_id=str(run["conversation_id"]), surface="web",
                      status="cancelled", run_status="cancelled")
            return True

    def _claim(
        self, uow: UnitOfWork, account_id: UUID, operation: str,
        key: str, payload: object
    ) -> CommandResult | None:
        digest = _digest(payload)
        row = self.idempotency.claim(
            uow, _id(), account_id, operation, key, digest,
            datetime.now(UTC) + timedelta(days=7),
        )
        if row is None:
            return None
        if row is None or bytes(row["request_hash"]) != digest:
            raise IdempotencyConflict()
        if row["status"] == "completed":
            return CommandResult(
                int(row["response_status"]),
                cast(dict[str, Any], row["response_body"]),
                replayed=True,
                resource_reused=(operation == "retry_run" and int(row["response_status"]) == 200),
            )
        raise ConversationBusy()

    def _complete(
        self, uow: UnitOfWork, account_id: UUID, operation: str, key: str,
        response_status: int, result: dict[str, Any]
    ) -> None:
        self.idempotency.complete(
            uow, account_id, operation, key, response_status, json.dumps(result)
        )

    def _send_result_for_run(self, uow: UnitOfWork, run_id: UUID) -> dict[str, Any]:
        snapshot = self._snapshot_for_run(uow, run_id)
        user = uow.execute(
            "SELECT m.* FROM messages m JOIN runs r ON r.trigger_message_id=m.message_id "
            "WHERE r.run_id=%s", (run_id,)
        ).fetchone()
        run = snapshot["run"]
        return {
            "message_id": user and str(user["message_id"]),
            "run_id": str(run_id),
            "session_id": run["session_id"],
            "user_message": self._message_dto(user),
            "assistant_message": snapshot["assistant_message"],
            "run": run,
            "events_url": f"/api/v1/runs/{run_id}/events",
        }

    def _retry_result_for_run(
        self, uow: UnitOfWork, source_run_id: UUID, run_id: UUID
    ) -> dict[str, Any]:
        snapshot = self._snapshot_for_run(uow, run_id)
        return {
            "run_id": str(run_id),
            "source_run_id": str(source_run_id),
            "retry_of_run_id": str(source_run_id),
            "assistant_message": snapshot["assistant_message"],
            "run": snapshot["run"],
            "events_url": f"/api/v1/runs/{run_id}/events",
        }

    def _snapshot_for_run(self, uow: UnitOfWork, run_id: UUID) -> dict[str, Any]:
        run = uow.execute("SELECT * FROM runs WHERE run_id=%s", (run_id,)).fetchone()
        message = uow.execute(
            "SELECT * FROM messages WHERE produced_by_run_id=%s", (run_id,)
        ).fetchone()
        return {"run": self._run_dto(run), "assistant_message": self._message_dto(message)}

    @staticmethod
    def _timestamp(value: datetime | None) -> str | None:
        return value.astimezone(UTC).isoformat(timespec="milliseconds").replace("+00:00", "Z") if value else None

    @classmethod
    def _conversation_dto(cls, row: Mapping[str, Any]) -> dict[str, Any]:
        return {
            "conversation_id": str(row["conversation_id"]), "title": row["title"],
            "status": row["status"], "last_message_seq": row["last_message_seq"],
            "metadata_version": row["metadata_version"],
            "created_at": cls._timestamp(row["created_at"]),
            "updated_at": cls._timestamp(row["updated_at"]),
        }

    @classmethod
    def _message_dto(cls, row: Mapping[str, Any]) -> dict[str, Any]:
        return {
            "message_id": str(row["message_id"]),
            "conversation_id": str(row["conversation_id"]), "role": row["role"],
            "status": row["status"], "content": row["content"],
            "sequence": row["sequence"],
            "client_request_id": str(row["client_request_id"]) if row["client_request_id"] else None,
            "produced_by_run_id": str(row["produced_by_run_id"]) if row["produced_by_run_id"] else None,
            "created_at": cls._timestamp(row["created_at"]),
            "completed_at": cls._timestamp(row["completed_at"]),
        }

    @classmethod
    def _run_dto(cls, row: Mapping[str, Any]) -> dict[str, Any]:
        failure = None
        if row["status"] == "failed":
            failure = {"code": row["failure_code"], "message": row["failure_message"] or "Agent 暂时无法完成本次请求，请稍后重试。", "retryable": True}
        return {
            "run_id": str(row["run_id"]), "conversation_id": str(row["conversation_id"]),
            "session_id": str(row["session_id"]),
            "trigger_message_id": str(row["trigger_message_id"]),
            "retry_of_run_id": str(row["retry_of_run_id"]) if row["retry_of_run_id"] else None,
            "status": row["status"], "failure": failure, "version": row["version"],
            "created_at": cls._timestamp(row["created_at"]),
            "started_at": cls._timestamp(row["started_at"]),
            "finished_at": cls._timestamp(row["finished_at"]),
            "updated_at": cls._timestamp(row["updated_at"]),
        }

    def _outbox(self, uow: UnitOfWork, account_id: UUID, conversation_id: UUID, run_id: UUID, event_type: str, terminal_status: str | None = None) -> None:
        key = f"terminal:{run_id}:{terminal_status}" if event_type == "publish_terminal_event" else f"{event_type.replace('_', '-')}:{run_id}"
        event_id = _id()
        payload = {"run_id": str(run_id), "version": 1}
        if terminal_status:
            payload["terminal_status"] = terminal_status
            payload["terminal_event_id"] = str(event_id)
        self.outbox.enqueue(
            uow, event_id, account_id, event_type, key, conversation_id, run_id,
            json.dumps(payload),
        )

    def _set_terminal(
        self, uow: UnitOfWork, account_id: UUID, conversation_id: UUID,
        run_id: UUID, status: str
    ) -> None:
        message_status = {"failed": "failed", "cancelled": "aborted"}[status]
        self.messages.set_terminal(uow, run_id, message_status)
        self.runs.set_terminal(uow, run_id, status)
        self._outbox(
            uow, account_id, conversation_id, run_id, "publish_terminal_event", status
        )

    def _lock_owned_run(
        self, uow: UnitOfWork, account_id: UUID, run_id: UUID
    ) -> dict[str, Any]:
        conversation_id = self.runs.discover_conversation(uow, account_id, run_id)
        if conversation_id is None:
            raise ResourceNotFound()
        conversation = self.conversations.get_for_account(
            uow, account_id, conversation_id, lock=True
        )
        if conversation is None:
            raise ResourceNotFound()
        run = self.runs.get_for_account(uow, account_id, run_id, lock=True)
        if run is None or run["conversation_id"] != conversation_id:
            raise ResourceNotFound()
        return cast(dict[str, Any], run)
