"""Phase-A transaction protocols. UUIDs are generated by the application, not SQL."""
from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime, timedelta
from typing import Any, cast
from uuid import UUID

from uuid6 import uuid7

from persistence.repositories import (
    AccountRepository,
    ConversationRepository,
    IdempotencyRepository,
    MessageRepository,
    OutboxRepository,
    RunRepository,
    SessionRepository,
    WorkflowExecutionRepository,
)
from persistence.uow import UnitOfWork, retryable_transaction

from .errors import ConversationBusy, IdempotencyConflict, ResourceNotFound


def _id() -> UUID:
    """Generate application-owned UUIDv7 values; PostgreSQL needs no UUID extension."""
    return uuid7()


def _digest(value: object) -> bytes:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).digest()


class CommandService:
    def __init__(self, database_url: str):
        self.database_url = database_url
        self.accounts = AccountRepository()
        self.conversations = ConversationRepository()
        self.messages = MessageRepository()
        self.runs = RunRepository()
        self.sessions = SessionRepository()
        self.workflows = WorkflowExecutionRepository()
        self.idempotency = IdempotencyRepository()
        self.outbox = OutboxRepository()

    @retryable_transaction
    def create_conversation(self, account_id: UUID, key: str, title: str = "") -> dict[str, str]:
        payload = {"title": title}
        with UnitOfWork(self.database_url) as uow:
            existing = self._claim(uow, account_id, "create_conversation", key, payload)
            if existing:
                return existing
            if not self.accounts.require_active(uow, account_id):
                raise ResourceNotFound()
            conversation_id = _id()
            self.conversations.create(uow, conversation_id, account_id, title)
            result = {"conversation_id": str(conversation_id)}
            self._complete(uow, account_id, "create_conversation", key, result)
            return result

    @retryable_transaction
    def send_message(self, account_id: UUID, conversation_id: UUID, key: str, content: str) -> dict[str, str]:
        payload = {"conversation_id": str(conversation_id), "content": content}
        with UnitOfWork(self.database_url) as uow:
            existing = self._claim(uow, account_id, "send_message", key, payload)
            if existing:
                return existing
            conversation = self.conversations.lock_active(uow, account_id, conversation_id)
            if not conversation:
                raise ResourceNotFound()
            retained = self.messages.find_initial_by_client_request(uow, account_id, UUID(key))
            if retained:
                if retained["conversation_id"] != conversation_id or retained["content"] != content:
                    raise IdempotencyConflict()
                result = {"message_id": str(retained["message_id"]), "run_id": str(retained["run_id"]), "session_id": str(retained["session_id"])}
                self._complete(uow, account_id, "send_message", key, result)
                return result
            if self.runs.has_active(uow, conversation_id):
                raise ConversationBusy()
            session_id = self.sessions.get_or_create_active(
                uow, account_id, conversation_id, _id()
            )
            allocated = self.conversations.allocate_messages(
                uow, account_id, conversation_id, 2
            )
            user_message_id, run_id, assistant_message_id = _id(), _id(), _id()
            workflow_id = f"hpagent-web-run-{run_id}"
            self.messages.insert_user(
                uow, user_message_id, account_id, conversation_id, content,
                allocated - 1, UUID(key)
            )
            self.runs.insert(
                uow, run_id, account_id, conversation_id, session_id, user_message_id,
                workflow_id, allocated - 1
            )
            self.messages.insert_assistant(
                uow, assistant_message_id, account_id, conversation_id, allocated, run_id
            )
            self._outbox(uow, account_id, conversation_id, run_id, "start_run")
            result = {"message_id": str(user_message_id), "run_id": str(run_id), "session_id": str(session_id)}
            self._complete(uow, account_id, "send_message", key, result)
            return result

    @retryable_transaction
    def cancel_run(self, account_id: UUID, run_id: UUID, key: str) -> dict[str, str]:
        """Cancel a queued Run before any Workflow execution exists.

        The Temporal-facing branch is deliberately not implemented here: Phase D
        owns it.  This branch still follows the approved Phase-A atomic terminal
        transaction and leaves the existing start event for a future dispatcher to
        observe and skip.
        """
        payload = {"run_id": str(run_id)}
        with UnitOfWork(self.database_url) as uow:
            existing = self._claim(uow, account_id, "cancel_run", key, payload)
            if existing:
                return existing
            conversation_id = self.runs.discover_conversation(uow, account_id, run_id)
            if conversation_id is None:
                raise ResourceNotFound()
            self.conversations.get_for_account(uow, account_id, conversation_id, lock=True)
            run = self.runs.get_for_account(uow, account_id, run_id, lock=True)
            if run is None:
                raise ResourceNotFound()
            if run["status"] in ("completed", "failed", "cancelled"):
                result = {"run_id": str(run_id), "status": run["status"]}
            elif run["status"] == "queued" and not self.workflows.has_current(uow, run_id):
                self._set_terminal(
                    uow, account_id, run["conversation_id"], run_id, "cancelled"
                )
                result = {"run_id": str(run_id), "status": "cancelled"}
            else:
                self.runs.set_cancelling(uow, run_id)
                self._outbox(uow, account_id, run["conversation_id"], run_id, "cancel_run")
                result = {"run_id": str(run_id), "status": "cancelling"}
            self._complete(uow, account_id, "cancel_run", key, result)
            return result

    @retryable_transaction
    def retry_run(self, account_id: UUID, source_run_id: UUID, key: str) -> dict[str, str]:
        payload = {"run_id": str(source_run_id)}
        with UnitOfWork(self.database_url) as uow:
            existing = self._claim(uow, account_id, "retry_run", key, payload)
            if existing:
                return existing
            conversation_id = self.runs.discover_conversation(uow, account_id, source_run_id)
            if conversation_id is None:
                raise ResourceNotFound()
            conversation = self.conversations.get_for_account(
                uow, account_id, conversation_id, lock=True
            )
            source = self.runs.get_for_account(uow, account_id, source_run_id, lock=True)
            if source is None:
                raise ResourceNotFound()
            child = self.runs.direct_retry(uow, source_run_id)
            if child:
                result = {"run_id": str(child)}
            else:
                if source["status"] not in ("failed", "cancelled"):
                    raise ConversationBusy()
                if conversation is None or conversation["status"] != "active":
                    raise ResourceNotFound()
                if self.runs.has_active(uow, source["conversation_id"]):
                    raise ConversationBusy()
                session_id = self.sessions.get_or_create_active(
                    uow, account_id, source["conversation_id"], _id()
                )
                sequence = self.conversations.allocate_messages(
                    uow, account_id, source["conversation_id"], 1
                )
                run_id = _id()
                self.runs.insert(
                    uow, run_id, account_id, source["conversation_id"], session_id,
                    source["trigger_message_id"], f"hpagent-web-run-{run_id}",
                    source["context_message_seq"], source_run_id
                )
                self.messages.insert_assistant(
                    uow, _id(), account_id, source["conversation_id"], sequence, run_id
                )
                self._outbox(uow, account_id, source["conversation_id"], run_id, "start_run")
                result = {"run_id": str(run_id)}
            self._complete(uow, account_id, "retry_run", key, result)
            return result

    @retryable_transaction
    def complete_run(self, account_id: UUID, run_id: UUID, content: str) -> bool:
        """Lifecycle adapter entrypoint; callers invoke it only after external work."""
        with UnitOfWork(self.database_url) as uow:
            run = self._lock_owned_run(uow, account_id, run_id)
            if run["status"] in ("completed", "failed", "cancelled"):
                return bool(run["status"] == "completed")
            if run["status"] not in ("running", "cancelling"):
                raise ConversationBusy()
            self.messages.set_terminal(uow, run_id, "completed", content)
            self.runs.set_terminal(uow, run_id, "completed")
            self._outbox(uow, account_id, run["conversation_id"], run_id, "retain_memory")
            self._outbox(uow, account_id, run["conversation_id"], run_id, "publish_terminal_event", "completed")
            return True

    @retryable_transaction
    def fail_run(self, account_id: UUID, run_id: UUID, failure_code: str, failure_message: str | None = None) -> bool:
        """Atomically record a safe terminal failure and its notification."""
        with UnitOfWork(self.database_url) as uow:
            run = self._lock_owned_run(uow, account_id, run_id)
            if run["status"] in ("completed", "failed", "cancelled"):
                return bool(run["status"] == "failed")
            self.messages.set_terminal(uow, run_id, "failed")
            self.runs.set_terminal(uow, run_id, "failed", failure_code, failure_message)
            self._outbox(uow, account_id, run["conversation_id"], run_id, "publish_terminal_event", "failed")
            return True

    @retryable_transaction
    def cancelled_run(self, account_id: UUID, run_id: UUID) -> bool:
        """Converge a Workflow cancellation callback into one atomic terminal fact."""
        with UnitOfWork(self.database_url) as uow:
            run = self._lock_owned_run(uow, account_id, run_id)
            if run["status"] in ("completed", "failed", "cancelled"):
                return bool(run["status"] == "cancelled")
            self.messages.set_terminal(uow, run_id, "aborted")
            self.runs.set_terminal(uow, run_id, "cancelled")
            self._outbox(
                uow, account_id, run["conversation_id"], run_id,
                "publish_terminal_event", "cancelled"
            )
            return True

    def _claim(self, uow: UnitOfWork, account_id: UUID, operation: str, key: str, payload: object) -> dict[str, str] | None:
        digest = _digest(payload)
        row = self.idempotency.claim(
            uow, _id(), account_id, operation, key, digest,
            datetime.now(UTC) + timedelta(days=7),
        )
        if row is None:
            return None
        if row is None or bytes(row["request_hash"]) != digest:
            raise IdempotencyConflict()
        if row["status"] == "completed":
            return cast(dict[str, str], row["response_body"])
        raise ConversationBusy()

    def _complete(self, uow: UnitOfWork, account_id: UUID, operation: str, key: str, result: dict[str, str]) -> None:
        self.idempotency.complete(uow, account_id, operation, key, json.dumps(result))

    def _outbox(self, uow: UnitOfWork, account_id: UUID, conversation_id: UUID, run_id: UUID, event_type: str, terminal_status: str | None = None) -> None:
        key = f"terminal:{run_id}:{terminal_status}" if event_type == "publish_terminal_event" else f"{event_type.replace('_', '-')}:{run_id}"
        event_id = _id()
        payload = {"run_id": str(run_id), "version": 1}
        if terminal_status:
            payload["terminal_status"] = terminal_status
            payload["terminal_event_id"] = str(event_id)
        self.outbox.enqueue(
            uow, event_id, account_id, event_type, key, conversation_id, run_id,
            json.dumps(payload),
        )

    def _set_terminal(
        self, uow: UnitOfWork, account_id: UUID, conversation_id: UUID,
        run_id: UUID, status: str
    ) -> None:
        message_status = {"failed": "failed", "cancelled": "aborted"}[status]
        self.messages.set_terminal(uow, run_id, message_status)
        self.runs.set_terminal(uow, run_id, status)
        self._outbox(
            uow, account_id, conversation_id, run_id, "publish_terminal_event", status
        )

    def _lock_owned_run(
        self, uow: UnitOfWork, account_id: UUID, run_id: UUID
    ) -> dict[str, Any]:
        conversation_id = self.runs.discover_conversation(uow, account_id, run_id)
        if conversation_id is None:
            raise ResourceNotFound()
        conversation = self.conversations.get_for_account(
            uow, account_id, conversation_id, lock=True
        )
        if conversation is None:
            raise ResourceNotFound()
        run = self.runs.get_for_account(uow, account_id, run_id, lock=True)
        if run is None or run["conversation_id"] != conversation_id:
            raise ResourceNotFound()
        return cast(dict[str, Any], run)
