from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from common.types import Event, UnifiedMessage, SessionMetadata


class ISession(ABC):
    """Session memory interface — stores and retrieves event history."""
    @abstractmethod
    async def create_session(self, metadata: SessionMetadata) -> str: ...
    @abstractmethod
    async def emit_event(self, event: Event) -> str: ...
    @abstractmethod
    async def get_events(self, session_id: str, offset: int = 0, limit: Optional[int] = None, event_types: Optional[List[str]] = None) -> List[Event]: ...
    @abstractmethod
    async def rewind_session(self, session_id: str, target_event_id: str) -> Dict[str, Any]: ...
    @abstractmethod
    async def archive_session(self, session_id: str) -> bool: ...
    @abstractmethod
    async def list_sessions(self, limit: int = 50, offset: int = 0, status: Optional[str] = None, tags: Optional[List[str]] = None) -> List[SessionMetadata]: ...


class IResources(ABC):
    """External resource access interface."""
    @abstractmethod
    async def initialize_models(self) -> None: ...
    @abstractmethod
    async def register_model(self, model_id: str, client: Any, priority: int = 0) -> None: ...
    @abstractmethod
    async def configure_fallback(self, group_name: str, primary: str, *fallbacks: str) -> None: ...
    @abstractmethod
    async def generate(self, model_selector: str, messages: List[Dict[str, Any]], tools: Optional[List[Dict[str, Any]]] = None, stream: bool = False) -> Any: ...
    @abstractmethod
    async def get_credential(self, resource_id: str, scope: List[str]) -> str: ...
    @abstractmethod
    async def proxy_request(self, target_url: str, method: str, resource_id: str, headers: Optional[Dict[str, str]] = None, body: Optional[Any] = None) -> Dict[str, Any]: ...


class ISandbox(ABC):
    """Sandbox interface — all external operations proxied through sandboxes (the hands)."""
    @abstractmethod
    async def execute(self, tool_name: str, arguments: Dict[str, Any]) -> Any: ...
    @abstractmethod
    async def list_tools(self) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def health_check(self) -> bool: ...


class IChannel(ABC):
    """Channel interface — message ingress/egress for sandbox hands."""
    @abstractmethod
    async def normalize_message(self, raw_message: Any) -> UnifiedMessage: ...
    @abstractmethod
    async def send_message(self, message: UnifiedMessage) -> bool: ...
    @abstractmethod
    async def start_monitor(self, callback_url: str) -> bool: ...
    @abstractmethod
    async def stop_monitor(self) -> bool: ...


class ITool(ABC):
    @property
    @abstractmethod
    def name(self) -> str: ...

    @property
    @abstractmethod
    def description(self) -> str: ...

    @property
    @abstractmethod
    def parameters(self) -> Dict[str, Any]: ...

    @abstractmethod
    async def execute(self, **kwargs) -> Any: ...
